openapi: 3.0.1
info:
  version: "1.0"
  title: "Resume subscription"
  description: |
   This API resumes subscription which has been canceled.
paths:
  /store/customers/me/subscriptions/{id}/resume:
    post:
      tags:
      - "subscription"
      summary: "Resuming subscription and returns account holder"
      parameters:
      - name: id
        in: path
        description: Subscription ID
        required: true
        schema:
          type: string
      responses:
        "200":
          description: "Returns account holder"
          content:
            application/json:
              schema:
                type: object
                properties:
                  accountHolderData:
                    type: object
        "400":
          description: "Not OK"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string