openapi: 3.0.1
info:
  version: "1.0"
  title: "Retry payment for subscription"
  description: |
   This API tries retry payment for failed subscription.
paths:
  /store/customers/me/subscriptions/{id}/retry-payment:
    post:
      tags:
      - "subscription"
      summary: "Retrying payment and returns account holder"
      parameters:
      - name: id
        in: path
        description: Subscription ID
        required: true
        schema:
          type: string
      responses:
        "200":
          description: "Returns account holder"
          content:
            application/json:
              schema:
                type: object
                properties:
                  checkoutSessionUrl:
                    type: string
        "400":
          description: "Not OK"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string